# -*- coding: utf-8 -*-
"""Final_Project_CSCI4521.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cHbBrZX7WMrEzHl8rVhPRALxp6HqNEfm
"""

!pip install datasets sentence-transformers -q

!pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git" -q
!pip install --no-deps "trl<0.9.0" peft accelerate bitsandbytes xformers datasets -q

import unsloth
from unsloth import FastLanguageModel
import torch

from datasets import load_dataset

dataset = load_dataset("dair-ai/emotion")

train_data = dataset["train"]
val_data = dataset["validation"]
test_data = dataset["test"]

print(train_data[8])

X_train_pre = train_data["text"]
y_train = train_data["label"]

X_val_pre = val_data["text"]
y_val = val_data["label"]

X_test_pre = test_data["text"]
y_test = test_data["label"]

label_names = dataset["train"].features["label"].names
print(label_names)

from sentence_transformers import SentenceTransformer

embed_model = SentenceTransformer("SamLowe/roberta-base-go_emotions")

X_train = embed_model.encode(X_train_pre, show_progress_bar=True)
X_val = embed_model.encode(X_val_pre, show_progress_bar=True)
X_test = embed_model.encode(X_test_pre, show_progress_bar=True)

print(X_train.shape)

input_dim = X_train.shape[1]  # should be 384
num_classes = len(label_names)  # 6
print(input_dim)
print(num_classes)

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, classification_report, confusion_matrix
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.optim as optim

class MLPClassifier(nn.Module):
    def __init__(self, input_dim, num_classes):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, 256),
            nn.BatchNorm1d(256),
            nn.ReLU(),
            nn.Dropout(0.3),

            nn.Linear(256, 128),
            nn.BatchNorm1d(128),
            nn.ReLU(),
            nn.Dropout(0.3),

            nn.Linear(128, num_classes)
        )
    def forward(self, x):
        return self.net(x)

MLP_model = MLPClassifier(input_dim=input_dim, num_classes=num_classes)

import torch

X_train_t = torch.tensor(X_train, dtype=torch.float32)
X_val_t = torch.tensor(X_val, dtype=torch.float32)

y_train_t = torch.tensor(y_train, dtype=torch.long)
y_val_t = torch.tensor(y_val, dtype=torch.long)

from torch.utils.data import TensorDataset, DataLoader

criterion = nn.CrossEntropyLoss(label_smoothing=0.1)
optimizer = torch.optim.AdamW(MLP_model.parameters(), lr=0.001, weight_decay=0.01)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=50)

batch_size = 100

train_dataset = TensorDataset(X_train_t, y_train_t)
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

train_losses = []
val_losses = []

for epoch in range(50):

    MLP_model.train()
    total_train_loss = 0

    for X_batch, y_batch in train_loader:
        optimizer.zero_grad()

        outputs = MLP_model(X_batch)
        loss = criterion(outputs, y_batch)

        loss.backward()
        optimizer.step()

        total_train_loss += loss.item() * X_batch.size(0)

    scheduler.step()

    avg_train_loss = total_train_loss / len(train_dataset)

    MLP_model.eval()
    with torch.no_grad():
        val_outputs = MLP_model(X_val_t)
        val_loss = criterion(val_outputs, y_val_t)

        preds = torch.argmax(val_outputs, dim=1)
        val_acc = (preds == y_val_t).float().mean().item()

    train_losses.append(avg_train_loss)
    val_losses.append(val_loss.item())

    if epoch % 10 == 0:
        print(
            f"Epoch {epoch}: "
            f"train loss={avg_train_loss:.4f}, "
            f"val loss={val_loss.item():.4f}, "
            f"val acc={val_acc:.4f}"
        )



plt.figure(figsize=(8, 5))

plt.plot(train_losses, label="Training Loss")
plt.plot(val_losses, label="Validation Loss")

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training vs Validation Loss")
plt.legend()
plt.grid(True)
plt.show()

MLP_model.eval()

with torch.no_grad():
    logits = MLP_model(X_val_t)   # or X_test_t if you have it
    preds = torch.argmax(logits, dim=1)

y_true = y_val_t.cpu().numpy()
y_pred = preds.cpu().numpy()

MLP_accuracy = accuracy_score(y_true, y_pred)

MLP_precision, MLP_recall, MLP_f1, MLP_support = precision_recall_fscore_support(
    y_true,
    y_pred,
    average="macro",
    zero_division=0
)

print("MLP Results")
print("Accuracy:", MLP_accuracy)
print("Macro Precision:", MLP_precision)
print("Macro Recall:", MLP_recall)
print("Macro F1:", MLP_f1)

!pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git" -q
!pip install --no-deps "trl<0.9.0" peft accelerate bitsandbytes xformers datasets -q

max_seq_length = 1024
dtype = None
load_in_4bit = True

llm_model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/llama-3-8b-bnb-4bit",
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit
)

FastLanguageModel.for_inference(llm_model)

def make_prompt(text):
    return f"""
    Class Labels: ['sadness', 'joy', 'love', 'anger', 'fear', 'surprise']

    text: {text}
    """

def ask_llm_unsloth(prompt):
    full_prompt = f"""### Instruction:
You are a precise classifier. Return only one class label from the provided list and a confidence level.

Follow this exact format:
label | confidence


The confidence must be a number from 0 to 1 and the label must be one of the provided class labels.

No Explanations
### Input:
{prompt}

### Answer:
"""

    inputs = tokenizer(
        full_prompt,
        return_tensors="pt",
        truncation=True,
        max_length=1024
    ).to("cuda")
    outputs = llm_model.generate(
        **inputs,
        max_new_tokens=20,
        do_sample=False,
        temperature=0.0,
        pad_token_id=tokenizer.eos_token_id
    )
    decoded = tokenizer.decode(outputs[0], skip_special_tokens=True)

    if "### Answer:" in decoded:
        decoded = decoded.split("### Answer:")[-1]

    response = decoded.strip()
    parts = response.split("|")
    if len(parts) == 2:
        label, confidence = parts
        confidence = float(confidence.strip())
    return label, confidence

import random




rand_indices = random.sample(range(len(X_test_pre)), 100)

predicted = []
actual = []
confidences = []
step = 0
for idx in rand_indices:
    prompt = make_prompt(X_test_pre[idx])
    predicted_label, confidence = ask_llm_unsloth(prompt)
    correct_label = label_names[y_test[idx]]
    if step % 25 == 0:
        print(f"Predicted: {predicted_label} Actual: {correct_label}")
    predicted.append(predicted_label)
    confidences.append(confidence)
    actual.append(correct_label)
    step +=1

LLM_accuracy = accuracy_score(actual, predicted)

LLM_precision, LLM_recall, LLM_f1, support = precision_recall_fscore_support(
    actual,
    predicted,
    average="macro",
    zero_division=0
)

print("Accuracy:", LLM_accuracy)
print("Macro Precision:", LLM_precision)
print("Macro Recall:", LLM_recall)
print("Macro F1:", LLM_f1)

metrics = ["Accuracy", "Precision", "Recall", "F1 Score"]

mlp_scores = [
    MLP_accuracy,
    MLP_precision,
    MLP_recall,
    MLP_f1
]

llm_scores = [
    LLM_accuracy,
    LLM_precision,
    LLM_recall,
    LLM_f1
]

x = np.arange(len(metrics))
width = 0.35

plt.figure(figsize=(9, 5))

plt.bar(x - width/2, mlp_scores, width, label="MLP")
plt.bar(x + width/2, llm_scores, width, label="LLM")

plt.xlabel("Metric")
plt.ylabel("Score")
plt.title("MLP vs LLM Performance Comparison")
plt.xticks(x, metrics)
plt.ylim(0, 1)
plt.legend()
plt.grid(axis="y", alpha=0.3)

plt.show()

most_conf = np.argsort(confidences)[-5:]
least_conf = np.argsort(confidences)[:5]

print("Most Confident Predictions:")
for idx in most_conf:
    print(f"Predicted: {predicted[idx]} Actual: {actual[idx]} Confidence: {confidences[idx]}")

print("\nLeast Confident Predictions:")
for idx in least_conf:
    print(f"Predicted: {predicted[idx]} Actual: {actual[idx]} Confidence: {confidences[idx]}")

import torch.nn.functional as F


MLP_model.eval()
with torch.no_grad():
    val_outputs = MLP_model(X_val_t)
    probs = F.softmax(val_outputs, dim=1)
    confidences_t, pred_indices = torch.max(probs, dim=1)

confidences = confidences_t.numpy()
predicted = [label_names[i] for i in pred_indices.numpy()]
actual = [label_names[i] for i in y_val_t.numpy()]

most_conf = np.argsort(confidences)[-5:]
least_conf = np.argsort(confidences)[:5]

print("Most Confident Predictions:")
for idx in most_conf:
    print(f"Predicted: {predicted[idx]} Actual: {actual[idx]} Confidence: {confidences[idx]:.4f}")

print("\nLeast Confident Predictions:")
for idx in least_conf:
    print(f"Predicted: {predicted[idx]} Actual: {actual[idx]} Confidence: {confidences[idx]:.4f}")

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

MLP_model.eval()

with torch.no_grad():
    logits = MLP_model(X_val_t)
    pred_ids = torch.argmax(logits, dim=1).cpu().numpy()

true_ids = np.array(y_test)

pred_labels = [label_names[i] for i in pred_ids]
true_labels = [label_names[i] for i in true_ids]

cm_mlp = confusion_matrix(
    true_labels,
    pred_labels,
    labels=label_names
)

plt.figure(figsize=(8, 8))

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm_mlp,
    display_labels=label_names
)

disp.plot(cmap="Blues", xticks_rotation=45)

plt.title("MLP Confusion Matrix")
plt.show()

cm_llm = confusion_matrix(
    actual,
    predicted,
    labels=label_names
)

plt.figure(figsize=(8, 8))

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm_llm,
    display_labels=label_names
)

disp.plot(cmap="Oranges", xticks_rotation=45)

plt.title("LLM Confusion Matrix")
plt.show()